version: '3.8'

services:
  calculator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Calculator API
      - APP_VERSION=0.1.0
      - DEBUG_MODE=False
      - PORT=8000
    restart: unless-stopped
    volumes:
      - ./:/app