site_name: Calculator API
site_description: A simple calculator API built with FastAPI following 12-Factor principles
site_author: Swoyesh Shrestha

repo_name: calculator-fastapi
repo_url: https://github.com/Swoyesh/Fusemachine_FastAPI.git

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: guide/getting-started.md